FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive
WORKDIR /export

RUN apt-get update && apt-get install -y wget gnupg2 lsb-release && rm -rf /var/lib/apt/lists/*
# Add Percona repository
RUN wget -qO - https://repo.percona.com/apt/percona-release_latest.generic_all.deb | dpkg -i -
# Enable xtrabackup repository
RUN percona-release enable-only tools release
# Download packages
RUN apt-get update && apt-get download percona-xtrabackup-80 libev4 libsnappy1v5 && rm -rf /var/lib/apt/lists/*
# Create archive
RUN tar -zcvf /xtrabackup-packages.tgz *.deb

FROM alpine:3.20
COPY --from=0 /xtrabackup-packages.tgz /packages/
CMD ["tail", "-f", "/dev/null"]
